### ISSUE TITLE
Question about socket error

### ISSUE THREAD

**Issue by trandzik** [JohannesDeml/Unity-Net-Core-Networking-Sockets#4]
Hi,
I know this isn't actually directly related to this repo, but I thought I might ask it here as you have forked NetCoreServer for use inside of Unity and therefore might have a clue about following error. 🙂

I am trying to use TCP Server functionality from NetCoreServer iside of Unity and everything seems to work fine except one little problem. When I compile for iOS or Android using IL2CPP and exit application with some established connection, I can't seem to afterwards reopen it and start the server without this error:
SocketException: Address already in use

When I wait about 30 seconds and try to restart the server, it works without any problem. I guess the socket somehow stays binded after closing the application - even though I explicitly use server.Close() before application exit.

Please have you by any chance encountered similar behavior? When I disconnect the client before closing the application, restarting works just fine. However it is kind of unfortunate to get blocked for some time in case I forget to disconnect the client before closing. Thanks for your time.

**Comment by JohannesDeml** [comment]
Hi,
not sure what you mean by explicitly calling `server.Close()`. Do you mean `Socket.Close()`?
From what I can tell looking at the sourcecode from NetCoreServer, there is no intention to expilicitly call the close method. take a look at the disconnect function: 
https://github.com/JohannesDeml/Unity-Net-Core-Networking-Sockets/blob/master/Assets/NetCoreNetworking/Scripts/Runtime/NetCoreServer/TcpClient.cs#L223-L234

It actally does everything for you. So my advice would be, to just use disconnect and not use close at all.
Does that make sense or am I missunderstanding your problem?

**Comment by trandzik** [comment]
Oh, I am very sorry - that was a mistake. I wanted to say that I explicitly use server.Stop() (from TcpServer class) before application exit.
https://github.com/chronoxor/NetCoreServer/blob/2fa0e672804e9adb8263b462a38921168f3b6130/source/NetCoreServer/TcpServer.cs#L207-L241

**Comment by JohannesDeml** [comment]
Oh okay, so you are using a unity application on a mobile device as a server? I didn't think that was the case and  therefore assumed you would be talking about socket.Close.

From what I can see there, it calls disconnect for all connected clients. Are you sure the application keeps running before all clients are disconnected? Maybe build your own Quit functionality that calls Application.Quit() in the end after you're sure everything else has shut down? Just a guess though, never had that use case.

**Comment by trandzik** [comment]
> Oh okay, so you are using a unity application on a mobile device as a server?

Yes, exactly.

> Are you sure the application keeps running before all clients are disconnected?

Yes, based on logs I can easily tell that all clients are disconnected (and that Stop() is completed) before application is exited.

> Maybe build your own Quit functionality

Right now I am using OnApplicationQuit() which seems to do exactly that - it executes its contents just before application exits.

> never had that use case

All right, don't worry about it. Anyway thank you very much for help. In case I would manage to figure out what is causing this problem I will post it here. :)

**Comment by JohannesDeml** [comment]
Sounds good.

Not sure what your use case is, but if you just want to easily share data on a local network, OSC might be easier to use than TCP, e.g. https://github.com/stella3d/OscCore
If you have a totally different use case, just ignore my suggestion :)

**Comment by trandzik** [comment]
Thanks, OSC would be nice, but unfortunately it won't suite my needs in this case as I need to send and receive quite large data with complex data structures. Therefore I am heading for raw TCP in this case. :) I have been also considering something like [Telepathy](https://github.com/vis2k/Telepathy) which seems to play along with Unity. However I haven't tested it yet.
